### PR TITLE
scala 2.13 support

### PR DESCRIPTION
**Pull request by fkowal**

### CODE REVIEW

**Comment by fkowal** [comment]
@davegurnell let me know if there is anything else to add

**Comment by davegurnell** [comment]
This looks great — thanks so much!

**Comment by fkowal** [comment]
That is great new.

Once the artifacts are published I'll be able to the make PR to https://github.com/davegurnell/bridges/issues/25

Sorry to burden you with the publishing process that's not pleasant from what I hear

**Comment by davegurnell** [comment]
No worries. I'll try to get them out. I'm having a bit of trouble at the moment though. I'm on a temporary laptop (mine is in for repair) and I'm having trouble getting signing and so on to work. I'll keep hacking on it.

(I need to set up some proper CI like with bridges.)

**Comment by davegurnell** [comment]
No... wait... did that just work? It did! Yaaaas!   

Version 1.1.1 is on Sonatype. 🎉

Thanks so much for your help!

**Comment by davegurnell** [comment]
One final note in case it comes up later...

I've simplified the branches in anticipation of setting up some proper CI.

I've deleted `develop` branch and switched to `master` as the default branch. At some point (hopefully soon) I'll set up Travis or Github Actions to automatically publish in the same manner as [bridges](https://github.com/davegurnell/bridges/commit/d158a23b84c52598ca85e97b873754ce2577cb0f).

**Pull request merged**
